// lib/firebase_options.dart
// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        return linux;
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAwHoLeTOieK98ENYQwWfqKLRFZp6TtOM8',
    appId: '1:880061436128:android:246e619e95c11053208085',
    messagingSenderId: '880061436128',
    projectId: 'expense-budget-fined-project',
    storageBucket: 'expense-budget-fined-project.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAwHoLeTOieK98ENYQwWfqKLRFZp6TtOM8',
    appId: '1:880061436128:ios:246e619e95c11053208085',
    messagingSenderId: '880061436128',
    projectId: 'expense-budget-fined-project',
    storageBucket: 'expense-budget-fined-project.firebasestorage.app',
    iosBundleId: 'com.FinEd_expense_tracker.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAwHoLeTOieK98ENYQwWfqKLRFZp6TtOM8',
    appId: '1:880061436128:ios:246e619e95c11053208085',
    messagingSenderId: '880061436128',
    projectId: 'expense-budget-fined-project',
    storageBucket: 'expense-budget-fined-project.firebasestorage.app',
    iosBundleId: 'com.FinEd_expense_tracker.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAwHoLeTOieK98ENYQwWfqKLRFZp6TtOM8',
    appId: '1:880061436128:web:246e619e95c11053208085',
    messagingSenderId: '880061436128',
    projectId: 'expense-budget-fined-project',
    storageBucket: 'expense-budget-fined-project.firebasestorage.app',
    authDomain: 'expense-budget-fined-project.firebaseapp.com',
  );

  static const FirebaseOptions linux = FirebaseOptions(
    apiKey: 'AIzaSyAwHoLeTOieK98ENYQwWfqKLRFZp6TtOM8',
    appId: '1:880061436128:web:246e619e95c11053208085',
    messagingSenderId: '880061436128',
    projectId: 'expense-budget-fined-project',
    storageBucket: 'expense-budget-fined-project.firebasestorage.app',
    authDomain: 'expense-budget-fined-project.firebaseapp.com',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAwHoLeTOieK98ENYQwWfqKLRFZp6TtOM8',
    appId: '1:880061436128:web:246e619e95c11053208085',
    messagingSenderId: '880061436128',
    projectId: 'expense-budget-fined-project',
    storageBucket: 'expense-budget-fined-project.firebasestorage.app',
    authDomain: 'expense-budget-fined-project.firebaseapp.com',
  );
}
